### ISSUE TITLE
Crash in Android 12 Samsung device

### ISSUE THREAD

**Issue by amkrys** [Aghajari/AXEmojiView#27]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.aghajari.emojiview.emoji.EmojiCategory[] com.aghajari.emojiview.AXEmojiManager.getCategories()' on a null object reference
        at com.aghajari.emojiview.view.AXSingleEmojiView.init(AXSingleEmojiView.java:195)
        at com.aghajari.emojiview.view.AXSingleEmojiView.<init>(AXSingleEmojiView.java:42)

**Comment by Aghajari** [comment]
Hi @amkrys , is this the original sample project?
